Stats: avoid trying to access formatter for unavailable locale (#43396)
* Stats: avoid trying to access formatter for unavailable locale

This should avoid errors like:

Fatal error: Uncaught ValueError: NumberFormatter::__construct(): Argument #1 ($locale) "skr" is invalid

Internal reference: p1746629628168729-slack-CDLH4C1UZ

Some of the locale codes we pass to NumberFormatter are not always available. `skr` is a good example.

* Extract locale check to speed up locale detection

See https://github.com/Automattic/jetpack/pull/43396#discussion_r2078167116

* Get locale with an underscore instead of dash

The dash is appropriate to display the language code in HTML, but is not valid ISO 639-3.

* Add test for new method

* Avoid static analysis error